export const THEME_PRESET_GROUP_ORDER = ["Core", "Warm", "Cool", "Electric", "Technical"] as const;
export type ThemePresetCategory = (typeof THEME_PRESET_GROUP_ORDER)[number];

export const THEME_PRESET_ORDER = [
  "light",
  "dark",
  "graphite",
  "polar",
  "sunset",
  "ember",
  "copperNight",
  "midnight",
  "aurora",
  "oceanGlass",
  "frostline",
  "ashenBlue",
  "vibrant",
  "neonDusk",
  "rosebyte",
  "velvet",
  "terminal",
] as const;

export type ThemePresetId = (typeof THEME_PRESET_ORDER)[number];
export type ThemeMode = "light" | "dark";
export type ThemePanelStyle = "soft" | "solid" | "outline";

export interface ThemeEditableTokens {
  primary: string;
  secondary: string;
  background: string;
  surface: string;
  accent: string;
  contrast: number;
  radius: number;
  spacing: number;
  panel: ThemePanelStyle;
}

export interface ThemePresetDefinition {
  id: ThemePresetId;
  label: string;
  description: string;
  category: ThemePresetCategory;
  mode: ThemeMode;
  text: string;
  muted: string;
  primaryForeground: string;
  success: string;
  danger: string;
  ambientA: string;
  ambientB: string;
  editable: ThemeEditableTokens;
}

export const THEME_PRESETS: Record<ThemePresetId, ThemePresetDefinition> = {
  light: {
    id: "light",
    label: "Light",
    description: "Clean, bright and calm.",
    category: "Core",
    mode: "light",
    text: "#132033",
    muted: "#617086",
    primaryForeground: "#09111b",
    success: "#1f8a5b",
    danger: "#c14a53",
    ambientA: "rgba(97, 167, 255, 0.18)",
    ambientB: "rgba(255, 209, 137, 0.16)",
    editable: {
      primary: "#3a84ff",
      secondary: "#5d87c2",
      background: "#f4f1ea",
      surface: "#fffdf7",
      accent: "#e8eef9",
      contrast: 1,
      radius: 1,
      spacing: 1,
      panel: "soft",
    },
  },
  dark: {
    id: "dark",
    label: "Dark",
    description: "Balanced, neutral and reliable.",
    category: "Core",
    mode: "dark",
    text: "#eef3fb",
    muted: "#98a6b9",
    primaryForeground: "#08111b",
    success: "#41b883",
    danger: "#ef6b73",
    ambientA: "rgba(57, 122, 255, 0.18)",
    ambientB: "rgba(39, 53, 78, 0.22)",
    editable: {
      primary: "#68b3ff",
      secondary: "#89c8ff",
      background: "#11161d",
      surface: "#171d26",
      accent: "#202937",
      contrast: 1,
      radius: 1,
      spacing: 1,
      panel: "soft",
    },
  },
  graphite: {
    id: "graphite",
    label: "Graphite",
    description: "Quiet charcoal with restrained contrast.",
    category: "Core",
    mode: "dark",
    text: "#edf0f3",
    muted: "#93a0ae",
    primaryForeground: "#0d1014",
    success: "#49b07a",
    danger: "#e46b6b",
    ambientA: "rgba(160, 178, 198, 0.14)",
    ambientB: "rgba(88, 99, 112, 0.2)",
    editable: {
      primary: "#8aa0b7",
      secondary: "#c2c8d0",
      background: "#171819",
      surface: "#1d2023",
      accent: "#262b30",
      contrast: 0.98,
      radius: 0.96,
      spacing: 0.98,
      panel: "solid",
    },
  },
  polar: {
    id: "polar",
    label: "Polar",
    description: "Icy, quiet and sharply readable.",
    category: "Core",
    mode: "light",
    text: "#102133",
    muted: "#5d7287",
    primaryForeground: "#0a121a",
    success: "#26825e",
    danger: "#c74e57",
    ambientA: "rgba(141, 197, 255, 0.18)",
    ambientB: "rgba(215, 240, 255, 0.22)",
    editable: {
      primary: "#4b8dff",
      secondary: "#6fb8db",
      background: "#eef4f7",
      surface: "#fbfdff",
      accent: "#e1ebf1",
      contrast: 1.02,
      radius: 0.98,
      spacing: 1,
      panel: "soft",
    },
  },
  sunset: {
    id: "sunset",
    label: "Sunset",
    description: "Warm, elegant and welcoming.",
    category: "Warm",
    mode: "dark",
    text: "#fff3ea",
    muted: "#d1b29e",
    primaryForeground: "#22110f",
    success: "#6ec49d",
    danger: "#ff8c7a",
    ambientA: "rgba(255, 143, 99, 0.22)",
    ambientB: "rgba(255, 205, 125, 0.16)",
    editable: {
      primary: "#f08a5d",
      secondary: "#f2b183",
      background: "#1a1413",
      surface: "#241b18",
      accent: "#34231d",
      contrast: 1.04,
      radius: 1.02,
      spacing: 1.02,
      panel: "soft",
    },
  },
  ember: {
    id: "ember",
    label: "Ember",
    description: "A darker firelight with richer reds.",
    category: "Warm",
    mode: "dark",
    text: "#fff1e7",
    muted: "#d0b29b",
    primaryForeground: "#21110d",
    success: "#6dc39c",
    danger: "#ff8677",
    ambientA: "rgba(255, 110, 72, 0.2)",
    ambientB: "rgba(255, 180, 102, 0.12)",
    editable: {
      primary: "#ff845a",
      secondary: "#ffb07b",
      background: "#1a120f",
      surface: "#231815",
      accent: "#331f18",
      contrast: 1.05,
      radius: 1.04,
      spacing: 1.02,
      panel: "soft",
    },
  },
  copperNight: {
    id: "copperNight",
    label: "Copper Night",
    description: "Metallic warmth with a quiet industrial edge.",
    category: "Warm",
    mode: "dark",
    text: "#f9efe9",
    muted: "#c9ad9e",
    primaryForeground: "#1d120e",
    success: "#6ab997",
    danger: "#ff8078",
    ambientA: "rgba(223, 122, 78, 0.18)",
    ambientB: "rgba(120, 84, 67, 0.16)",
    editable: {
      primary: "#d98a5a",
      secondary: "#b76b46",
      background: "#161110",
      surface: "#201716",
      accent: "#2c1e1a",
      contrast: 1.02,
      radius: 0.98,
      spacing: 1,
      panel: "solid",
    },
  },
  midnight: {
    id: "midnight",
    label: "Midnight",
    description: "Deep, cold and premium.",
    category: "Cool",
    mode: "dark",
    text: "#edf4ff",
    muted: "#97a5c0",
    primaryForeground: "#081018",
    success: "#49bfaa",
    danger: "#f07587",
    ambientA: "rgba(90, 153, 255, 0.2)",
    ambientB: "rgba(91, 107, 255, 0.14)",
    editable: {
      primary: "#76b0ff",
      secondary: "#8f7bff",
      background: "#0b1220",
      surface: "#10192a",
      accent: "#18243c",
      contrast: 1.06,
      radius: 1,
      spacing: 1,
      panel: "solid",
    },
  },
  aurora: {
    id: "aurora",
    label: "Aurora",
    description: "Teal and lilac light over a dark sky.",
    category: "Cool",
    mode: "dark",
    text: "#edf8ff",
    muted: "#93acc2",
    primaryForeground: "#091018",
    success: "#46c29c",
    danger: "#ff7f95",
    ambientA: "rgba(95, 224, 210, 0.2)",
    ambientB: "rgba(130, 123, 255, 0.15)",
    editable: {
      primary: "#69e5d0",
      secondary: "#8d82ff",
      background: "#0d141a",
      surface: "#121d25",
      accent: "#1a2b36",
      contrast: 1.05,
      radius: 1.04,
      spacing: 1,
      panel: "soft",
    },
  },
  oceanGlass: {
    id: "oceanGlass",
    label: "Ocean Glass",
    description: "Cool glassy surfaces with sea-blue edges.",
    category: "Cool",
    mode: "dark",
    text: "#eff7ff",
    muted: "#95adbf",
    primaryForeground: "#091219",
    success: "#4ec8a4",
    danger: "#ff8791",
    ambientA: "rgba(98, 191, 255, 0.18)",
    ambientB: "rgba(90, 255, 221, 0.12)",
    editable: {
      primary: "#79c6ff",
      secondary: "#62f0d7",
      background: "#0f171c",
      surface: "#132128",
      accent: "#1b3037",
      contrast: 1.04,
      radius: 1.06,
      spacing: 1.02,
      panel: "outline",
    },
  },
  frostline: {
    id: "frostline",
    label: "Frostline",
    description: "A crisp pale UI with cool, quiet accents.",
    category: "Cool",
    mode: "light",
    text: "#10212e",
    muted: "#667b8e",
    primaryForeground: "#09131a",
    success: "#2b8b6b",
    danger: "#c85960",
    ambientA: "rgba(148, 200, 255, 0.18)",
    ambientB: "rgba(255, 255, 255, 0.2)",
    editable: {
      primary: "#5ea9ff",
      secondary: "#90c5ff",
      background: "#f2f7fb",
      surface: "#ffffff",
      accent: "#e5eef5",
      contrast: 1.01,
      radius: 1.02,
      spacing: 1.02,
      panel: "outline",
    },
  },
  ashenBlue: {
    id: "ashenBlue",
    label: "Ashen Blue",
    description: "Muted blue-gray for quieter work sessions.",
    category: "Cool",
    mode: "dark",
    text: "#edf4fb",
    muted: "#96a6b6",
    primaryForeground: "#0a1016",
    success: "#4ab386",
    danger: "#ea7581",
    ambientA: "rgba(120, 146, 181, 0.18)",
    ambientB: "rgba(73, 89, 112, 0.16)",
    editable: {
      primary: "#8ca8c7",
      secondary: "#6f86a8",
      background: "#131a22",
      surface: "#18212b",
      accent: "#223143",
      contrast: 1.01,
      radius: 0.98,
      spacing: 1,
      panel: "solid",
    },
  },
  vibrant: {
    id: "vibrant",
    label: "Vibrant",
    description: "Energetic, crisp and still usable.",
    category: "Electric",
    mode: "dark",
    text: "#f4f7ff",
    muted: "#9ba6d1",
    primaryForeground: "#10111a",
    success: "#4ac090",
    danger: "#ff7b88",
    ambientA: "rgba(94, 240, 255, 0.2)",
    ambientB: "rgba(176, 93, 255, 0.16)",
    editable: {
      primary: "#78f0ff",
      secondary: "#cf7dff",
      background: "#13111d",
      surface: "#1a1630",
      accent: "#261d4a",
      contrast: 1.08,
      radius: 1.06,
      spacing: 1.02,
      panel: "outline",
    },
  },
  neonDusk: {
    id: "neonDusk",
    label: "Neon Dusk",
    description: "Controlled neon without turning the app into a toy.",
    category: "Electric",
    mode: "dark",
    text: "#f7f6ff",
    muted: "#a59ac9",
    primaryForeground: "#140f1b",
    success: "#53d3a4",
    danger: "#ff7aa6",
    ambientA: "rgba(108, 237, 255, 0.18)",
    ambientB: "rgba(229, 104, 255, 0.16)",
    editable: {
      primary: "#82f4ff",
      secondary: "#e278ff",
      background: "#151021",
      surface: "#1b1430",
      accent: "#281c48",
      contrast: 1.1,
      radius: 1.08,
      spacing: 1.03,
      panel: "outline",
    },
  },
  rosebyte: {
    id: "rosebyte",
    label: "Rosebyte",
    description: "A rosy dark palette with softer contrast.",
    category: "Electric",
    mode: "dark",
    text: "#fff4f8",
    muted: "#cda4b5",
    primaryForeground: "#1f1015",
    success: "#5cc59a",
    danger: "#ff7c95",
    ambientA: "rgba(255, 129, 177, 0.18)",
    ambientB: "rgba(153, 118, 255, 0.12)",
    editable: {
      primary: "#ff8fb8",
      secondary: "#b48cff",
      background: "#1a1016",
      surface: "#241720",
      accent: "#362233",
      contrast: 1.07,
      radius: 1.05,
      spacing: 1.02,
      panel: "soft",
    },
  },
  velvet: {
    id: "velvet",
    label: "Velvet",
    description: "Dark plum with a heavier, late-night feel.",
    category: "Electric",
    mode: "dark",
    text: "#f8f2ff",
    muted: "#b9a6cb",
    primaryForeground: "#120c18",
    success: "#51c39b",
    danger: "#ff8491",
    ambientA: "rgba(188, 109, 255, 0.18)",
    ambientB: "rgba(83, 72, 157, 0.16)",
    editable: {
      primary: "#bf7cff",
      secondary: "#8f72ff",
      background: "#140f1a",
      surface: "#1d1526",
      accent: "#2a1d3a",
      contrast: 1.04,
      radius: 1.08,
      spacing: 1,
      panel: "solid",
    },
  },
  terminal: {
    id: "terminal",
    label: "Terminal",
    description: "Green-lit, technical and intentionally utilitarian.",
    category: "Technical",
    mode: "dark",
    text: "#e8ffe4",
    muted: "#91b898",
    primaryForeground: "#09140c",
    success: "#6de693",
    danger: "#ff8f7a",
    ambientA: "rgba(116, 255, 151, 0.18)",
    ambientB: "rgba(39, 88, 53, 0.2)",
    editable: {
      primary: "#7dff9a",
      secondary: "#4fb66b",
      background: "#0e120f",
      surface: "#131914",
      accent: "#1d2820",
      contrast: 1.03,
      radius: 0.92,
      spacing: 0.96,
      panel: "outline",
    },
  },
};

export const DEFAULT_THEME_PRESET: ThemePresetId = "dark";

export function getThemePreset(id: ThemePresetId) {
  return THEME_PRESETS[id];
}

export function createThemeTokensFromPreset(id: ThemePresetId): ThemeEditableTokens {
  return { ...THEME_PRESETS[id].editable };
}
